### ISSUE TITLE
Docker Container Not Working

### ISSUE THREAD

**Issue by sleepsterz** [kuruoujou/aniping#1] opened 2017-10-18 16:48 UTC
I have tried to set this up on two separate occasions and both times I came up empty-handed. I was just wondering if the docker version of this is actually working or not.

**Comment by kuruoujou** [comment] 2017-10-18 17:07
Really? Hmm. I can't look closely right now, but can you provide the output
of `docker logs [container name]`? There may be some config setting I've
forgotten to document or a real bug in deployment.

Just to confirm, you already have sonarr set up, right?

Maybe I should consider a read only mode that doesn't require a backend or
any configuration.

**Comment by sleepsterz** [comment] 2017-10-18 19:41
Yep, I've already got sonarr setup. I will have to deploy the docker again tonight and I will grab those logs for you.

**Comment by sleepsterz** [comment] 2017-10-18 20:15
Here is the docker log i just pulled `[uWSGI] getting INI configuration from /etc/uwsgi/apps-enabled/uwsgi.ini
*** Starting uWSGI 2.0.15 (64bit) on [Wed Oct 18 21:50:01 2017] ***
compiled with version: 5.3.0 on 08 October 2017 00:44:16
os: Linux-4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017
nodename: f06a309e3cae
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /
detected binary path: /usr/local/bin/uwsgi
setgid() to 82
set additional group 101 (nginx)
setuid() to 100
chdir() to /app
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.socket fd 3
Python version: 3.5.4 (default, Sep 13 2017, 14:43:47)  [GCC 5.3.0]
Python main interpreter initialized at 0x5555d9e40ec0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145520 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /app/ to pythonpath.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 12, cores: 1)
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "FrontEnd.scrape_shows" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5555d9e40ec0 pid: 12 (default app)
[pid: 12|app: 0|req: 1/1] 98.111.8.205 () {42 vars in 767 bytes} [Wed Oct 18 21:53:45 2017] GET / => generated 4567 bytes in 293 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/app/aniping/front_end.py", line 434, in scrape_shows
    local_apm.plugin_category_function("scraper", "scrape_shows")
  File "/app/aniping/plugins.py", line 124, in plugin_category_function
    output.append(getattr(cls,func)(*args, **kwargs))
  File "/app/aniping/scraper/anilist.py", line 116, in scrape_shows
    self._update_show(show['id'])
  File "/app/aniping/scraper/anilist.py", line 130, in wrapper
    return func(self, *args, **kwargs)
  File "/app/aniping/scraper/anilist.py", line 272, in _update_show
    show = self._get_remote_show_info(aid)
  File "/app/aniping/scraper/anilist.py", line 130, in wrapper
    return func(self, *args, **kwargs)
  File "/app/aniping/scraper/anilist.py", line 239, in _get_remote_show_info
    with open(os.path.join(self._image_cache,filename), 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'static/images/cache/20791-qBVKnfdWc8fa.jpg'

[pid: 12|app: 0|req: 2/2] 98.111.8.205 () {42 vars in 763 bytes} [Wed Oct 18 21:53:55 2017] GET /static/favicon.ico => generated 233 bytes in 5 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 3/3] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:54:25 2017] GET / => generated 4567 bytes in 117 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 4/4] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:54:56 2017] GET / => generated 4567 bytes in 121 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 5/5] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:55:27 2017] GET / => generated 4567 bytes in 189 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 6/6] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:55:58 2017] GET / => generated 4567 bytes in 151 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 7/7] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:56:29 2017] GET / => generated 4567 bytes in 172 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 8/8] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:57:00 2017] GET / => generated 4567 bytes in 234 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 9/9] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:57:31 2017] GET / => generated 4567 bytes in 187 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 10/10] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:58:02 2017] GET / => generated 4567 bytes in 148 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 11/11] 98.111.8.205 () {44 vars in 808 bytes} [Wed Oct 18 21:58:14 2017] GET / => generated 4567 bytes in 131 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 12/12] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:58:45 2017] GET / => generated 4567 bytes in 155 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 13/13] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:59:15 2017] GET / => generated 4567 bytes in 166 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 14/14] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 21:59:47 2017] GET / => generated 4567 bytes in 186 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 15/15] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:00:18 2017] GET / => generated 4567 bytes in 223 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 16/16] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:00:49 2017] GET / => generated 4567 bytes in 156 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 17/17] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:01:20 2017] GET / => generated 4567 bytes in 132 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 18/18] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:01:51 2017] GET / => generated 4567 bytes in 213 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 19/19] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:02:22 2017] GET / => generated 4567 bytes in 177 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 20/20] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:02:53 2017] GET / => generated 4567 bytes in 130 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 21/21] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:03:24 2017] GET / => generated 4567 bytes in 135 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 22/22] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:03:55 2017] GET / => generated 4567 bytes in 162 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 23/23] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:04:26 2017] GET / => generated 4567 bytes in 185 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 24/24] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:04:57 2017] GET / => generated 4567 bytes in 133 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 25/25] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:05:28 2017] GET / => generated 4567 bytes in 139 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 26/26] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:05:59 2017] GET / => generated 4567 bytes in 128 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 27/27] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:06:30 2017] GET / => generated 4567 bytes in 138 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 28/28] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:07:01 2017] GET / => generated 4567 bytes in 131 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 29/29] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:07:32 2017] GET / => generated 4567 bytes in 126 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 30/30] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:08:03 2017] GET / => generated 4567 bytes in 184 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 31/31] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:08:34 2017] GET / => generated 4567 bytes in 141 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 32/32] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:09:05 2017] GET / => generated 4567 bytes in 183 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 33/33] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:09:36 2017] GET / => generated 4567 bytes in 153 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 34/34] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:10:07 2017] GET / => generated 4567 bytes in 158 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 35/35] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:10:38 2017] GET / => generated 4567 bytes in 159 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 36/36] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:11:09 2017] GET / => generated 4567 bytes in 103 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 37/37] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:11:40 2017] GET / => generated 4567 bytes in 208 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 38/38] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:12:11 2017] GET / => generated 4567 bytes in 109 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 39/39] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:12:42 2017] GET / => generated 4567 bytes in 239 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 40/40] 98.111.8.205 () {44 vars in 808 bytes} [Wed Oct 18 22:13:10 2017] GET / => generated 4567 bytes in 179 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 12|app: 0|req: 41/41] 98.111.8.205 () {46 vars in 839 bytes} [Wed Oct 18 22:13:42 2017] GET / => generated 4567 bytes in 195 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)`

**Comment by sleepsterz** [comment] 2017-10-18 20:20
Alright i have pulled my docker logs. How would you like me to send them over to you?

**Comment by kuruoujou** [comment] 2017-10-18 20:58
No worries, the log you already dropped in tells me what I need to know -
it's a permissions issue. I'll take a look at it tonight, and at the very
least give you a workaround.

Thank you for reporting this.

**Comment by kuruoujou** [comment] 2017-10-19 05:05
One more question: How are you invoking the container? Are you using adding the image cache (`/app/static/images/cache`) as a volume? If not, I have some more debugging to do. If so, then the problem is permissions with the directory you're passing into it - for now, though it's not pretty, the easiest way to fix it is to give the directory 777 permissions. To do that in Linux, go into the terminal and type `sudo chmod 777 /path/to/your/cache`, in Windows you need to give "Everyone" Read/Write permissions, but I don't remember off-hand how to do that.

If you're not using an external volume, you can try using one - the container should be able to make it on it's own at a directory you specify (using `-v /path/to/your/image/cache:/app/static/images/cache`, or if not, you can create a directory at that location and following the instructions above to give it global read/write permissions. The only things stored in this directory are images pulled from the web, so it should be fine to be globally writable, though it's certainly less than ideal.

If you still have problems, you might try to do the same thing with the database path (`/app/db`), as mentioned in the readme.

I'll debug it a bit more tomorrow if I have time, but I'll certainly have more time over the weekend to take a look. You can drop your logs here, or in a [gist](https://gist.github.com/) if you think it's too long.

**Comment by sleepsterz** [comment] 2017-10-19 05:15
Alright thank you for taking a look. I will have a go at it tomorrow and
report back.

**Comment by kuruoujou** [comment] 2017-10-20 04:09
I found the bug. I think, anyway - I was able to reproduce the problem you were seeing at least. Docker was creating the cache directory when the container started because it didn't exist, but when it was doing so it was doing it as root, and in the container it's the nginx user and www-data group that need to access it. I just have the Dockerfile create the directories now, before it fixes the permissions on everything in the build. `docker pull kuroshi/aniping` again to get the latest version, and you should be able to run it.

Having said that, I do recommend putting at least the database and image directory in a volume outside the container, just to make restarting the container or destroying and recreating it (let's say for updates or something) more painless. While it will work just fine without it because state is stored in sonarr, it'll have to refresh the cache from anilist during the first run again, and that can be slow. It works either way, though.

Please pull the container again and give it another go, and let me know if it works for you. If so, you can close this issue. Thanks again for reporting this!

**Comment by sleepsterz** [comment] 2017-10-20 06:48
Alright. I was able to resolve it by assigning read write permissions to the directories that were used. I will go ahead and pull the docker again tomorrow to update it.

**Comment by sleepsterz** [comment] 2017-10-20 06:49
Alright. I was able to resolve it by assigning read write permissions to the directories that were used. I will go ahead and pull the docker again tomorrow to update it.

**Comment by kuruoujou** [comment] 2017-10-21 21:50
Great! Glad to hear it's working. Please don't hesitate to open issues if you find problems or have questions.

**Closed as completed by kuruoujou** 2017-10-21 21:50 UTC
Labels: bug
